# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  # CHANGE BEFORE DEPLOYING, RUN `rake secret`
  secret_key_base: <58bd892d455410cc6a95d0a9b2babbf42105e1817e3fabf45777aa3cc5515986cdc99c2acb2c139e539db6c6113c4560c72eb9acf73012a7f48c201baf3b8e6c>

test:
  # CHANGE BEFORE DEPLOYING, RUN `rake secret`
  secret_key_base: <054cfade34f43ba07133cd937663398aae69d450b36763970e4b78f53cb3df14585a257db42814cefc823b1f5854917f54f496872365b5aabcb1c4ad862a377c>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <58bd892d455410cc6a95d0a9b2babbf42105e1817e3f25twqygdbashcjs7aa3cc5515986cdc99c2acb2c139e539db6c6113c4560c72eb9acf73012a7f48c201baf3b8e6c>